// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBXXOF-o8Opca_Hd3PqoFI5DZegN0Wik',
    appId: '1:289769567173:web:383a543ffd2293edbbd1ac',
    messagingSenderId: '289769567173',
    projectId: 'crews-auto',
    authDomain: 'crews-auto.firebaseapp.com',
    storageBucket: 'crews-auto.appspot.com',
    measurementId: 'G-K2F7VZMWT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9ZFCS1REaC607SOUwrNumAZNvz3MWN0',
    appId: '1:289769567173:android:218fcc0c91316376bbd1ac',
    messagingSenderId: '289769567173',
    projectId: 'crews-auto',
    storageBucket: 'crews-auto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5ZHc0LtkMhdCPTd_0Jk-Agt2TJDy2-o',
    appId: '1:289769567173:ios:0529e9fec40688cbbbd1ac',
    messagingSenderId: '289769567173',
    projectId: 'crews-auto',
    storageBucket: 'crews-auto.appspot.com',
    iosBundleId: 'com.example.flutterCarService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5ZHc0LtkMhdCPTd_0Jk-Agt2TJDy2-o',
    appId: '1:289769567173:ios:0529e9fec40688cbbbd1ac',
    messagingSenderId: '289769567173',
    projectId: 'crews-auto',
    storageBucket: 'crews-auto.appspot.com',
    iosBundleId: 'com.example.flutterCarService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBXXOF-o8Opca_Hd3PqoFI5DZegN0Wik',
    appId: '1:289769567173:web:1b32459eaceaa6adbbd1ac',
    messagingSenderId: '289769567173',
    projectId: 'crews-auto',
    authDomain: 'crews-auto.firebaseapp.com',
    storageBucket: 'crews-auto.appspot.com',
    measurementId: 'G-5QQP7DDNBG',
  );
}
